services:
  backend:
    build: # ビルドに使うDockerファイルのパス
      context: .
      dockerfile: ./backend/build/package/Dockerfile
    volumes: # マウントディレクトリ
      - ./:/app
    env_file: # .envファイル
      - ./backend/build/package/.env
    ports:
      - 8080:8080
